server.port=8081
spring.ai.ollama.api-key=${OLLAMA_API_KEY}
spring.threads.virtual.enabled=true
logging.level.root=INFO

management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
management.endpoint.shutdown.enabled=true

811260
62886
102952
158295